@extends('themes.fvft.layouts.master')
@section('style')
	@yield('css')
@endsection
@section('main')
        @include('themes.fvft.site.components.header')
		@yield('content')
		@include('themes.fvft.site.components.footer')
@endsection
@section('script')
		@yield('js')
@endsection